CREATE INDEX building_idx ON building USING btree(minerals, vespene_gas, supply);
CREATE INDEX unit_idx ON unit USING hash(unit_name);
CREATE INDEX hero_idx ON hero USING hash(hero_name);
CREATE INDEX map_idx ON map USING hash(map_name);
CREATE INDEX obstacle_idx ON obstacle USING hash(obstacle_name);
CREATE INDEX unit_health_id_idx ON unit (health_id);
CREATE INDEX unit_damage_id_idx ON unit (damage_id);
CREATE INDEX resource_patch_map_id_idx ON resource_patch (map_id);
CREATE INDEX resource_patch_resource_type_id_idx ON resource_patch (resource_type_id);
CREATE INDEX unit_monologue_unit_id_idx ON unit_monologue (unit_id);
CREATE INDEX hero_monologue_hero_id_idx ON hero_monologue (hero_id);
